# Change these first
owner: zweitstimme-org # Your GitHub organization or username, where this repository lives
repo: uptime # name of this repository

sites:
  - name: zweitstimme.org
    url: https://zweitstimme.org


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  baseUrl: /uptime
  logoUrl: https://zweitstimme.org/images/logo_orange.png
  name: Status
  introTitle: "Chek the availability of **zweitstimme.org**"
  introMessage: Find all the services provided by **zweitstimme.org** here and check their operational status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
